apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-frontend
  template:
    metadata:
      labels:
        app: events-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/example/events-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "http://events-dev.example.com/api"
            - name: API_BASE_URL
              value: "http://events-api:8000"
